// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QRMenu.API.Data;

#nullable disable

namespace QRMenu.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QRMenu.API.Models.Category", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Description").HasColumnType("text");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<string>("Name").IsRequired().HasColumnType("text");
                b.Property<int>("SortOrder").HasColumnType("integer");
                b.HasKey("Id");
                b.ToTable("Categories");
                b.HasData(
                    new { Id = 1, IsActive = true, Name = "Başlangıçlar", Description = "Meze ve salatalar", SortOrder = 1 },
                    new { Id = 2, IsActive = true, Name = "Ana Yemekler", Description = "Sıcak yemekler", SortOrder = 2 },
                    new { Id = 3, IsActive = true, Name = "İçecekler", Description = "Soğuk ve sıcak içecekler", SortOrder = 3 },
                    new { Id = 4, IsActive = true, Name = "Tatlılar", Description = "Tatlı çeşitleri", SortOrder = 4 });
            });

            modelBuilder.Entity("QRMenu.API.Models.MenuItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("CategoryId").HasColumnType("integer");
                b.Property<string>("Description").HasColumnType("text");
                b.Property<string>("ImagePath").HasColumnType("text");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<bool>("IsAvailable").HasColumnType("boolean");
                b.Property<string>("Name").IsRequired().HasColumnType("text");
                b.Property<decimal>("Price").HasColumnType("numeric(10,2)");
                b.Property<int>("SortOrder").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("CategoryId");
                b.ToTable("MenuItems");
            });

            modelBuilder.Entity("QRMenu.API.Models.Order", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("CustomerName").IsRequired().HasColumnType("text");
                b.Property<string>("Notes").HasColumnType("text");
                b.Property<int>("Status").HasColumnType("integer");
                b.Property<int>("TableId").HasColumnType("integer");
                b.Property<decimal>("TotalAmount").HasColumnType("numeric(10,2)");
                b.HasKey("Id");
                b.HasIndex("TableId");
                b.ToTable("Orders");
            });

            modelBuilder.Entity("QRMenu.API.Models.OrderItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("MenuItemId").HasColumnType("integer");
                b.Property<string>("Notes").HasColumnType("text");
                b.Property<int>("OrderId").HasColumnType("integer");
                b.Property<int>("Quantity").HasColumnType("integer");
                b.Property<decimal>("UnitPrice").HasColumnType("numeric(10,2)");
                b.HasKey("Id");
                b.HasIndex("MenuItemId");
                b.HasIndex("OrderId");
                b.ToTable("OrderItems");
            });

            modelBuilder.Entity("QRMenu.API.Models.Table", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Description").HasColumnType("text");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<string>("QRCodePath").IsRequired().HasColumnType("text");
                b.Property<string>("TableNumber").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("Tables");
                b.HasData(
                    new { Id = 1, IsActive = true, QRCodePath = "", TableNumber = "1", Description = "Pencere kenarı" },
                    new { Id = 2, IsActive = true, QRCodePath = "", TableNumber = "2", Description = "Bahçe" },
                    new { Id = 3, IsActive = true, QRCodePath = "", TableNumber = "3", Description = "İç mekan" });
            });

            modelBuilder.Entity("QRMenu.API.Models.MenuItem", b =>
            {
                b.HasOne("QRMenu.API.Models.Category", "Category")
                    .WithMany("MenuItems")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Category");
            });

            modelBuilder.Entity("QRMenu.API.Models.Order", b =>
            {
                b.HasOne("QRMenu.API.Models.Table", "Table")
                    .WithMany("Orders")
                    .HasForeignKey("TableId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Table");
            });

            modelBuilder.Entity("QRMenu.API.Models.OrderItem", b =>
            {
                b.HasOne("QRMenu.API.Models.MenuItem", "MenuItem")
                    .WithMany("OrderItems")
                    .HasForeignKey("MenuItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.HasOne("QRMenu.API.Models.Order", "Order")
                    .WithMany("OrderItems")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("MenuItem");
                b.Navigation("Order");
            });

            modelBuilder.Entity("QRMenu.API.Models.Category", b => { b.Navigation("MenuItems"); });
            modelBuilder.Entity("QRMenu.API.Models.Order", b => { b.Navigation("OrderItems"); });
            modelBuilder.Entity("QRMenu.API.Models.Table", b => { b.Navigation("Orders"); });
#pragma warning restore 612, 618
        }
    }
}
